id: system_settings_assistant_disable
title: "Disable Assistant"
discussion: |
  This is required for compliance with the DISA STIG for macOS.

  This is not a documented setting for *com.apple.ironwood.support*.

  link:https://developer.apple.com/documentation/devicemanagement/parentalcontroldictationandprofanity/[]
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.ironwood.support')\
  .objectForKey('Assistant Allowed').js
  EOS
result:
  string: "false"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-92946-3
  cci:
    - CCI-000381
    - CCI-001774
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - SRG-OS-000095-GPOS-00049
    - SRG-OS-000370-GPOS-00155
  disa_stig:
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - N/A
    controls v8:
      - N/A
macOS:
  - "14.0"
tags:
  - none
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.ironwood.support:
    "Assistant Allowed": false